apiVersion: v1
kind: Service
metadata:
  name: {{ include "highlight.fullname" . }}-kafka
  labels:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/part-of: {{ include "highlight.name" . }}
    {{- include "highlight.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/component: kafka
    app.kubernetes.io/part-of: {{ include "highlight.name" . }}
    {{- include "highlight.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.kafka.config.port | int }}
      protocol: TCP