services:
    file-collector:
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        container_name: filelog-collector
        image: otel/opentelemetry-collector-contrib
        command:
            - '--config=/etc/otel-collector-config.yaml'
        volumes:
            - ./otel-collector.yaml:/etc/otel-collector-config.yaml
            - $EXAMPLE_LOG_FILE_PATH:/var/log/watch.log
