[tool.poetry]
name = "highlight-io"
version = "0.6.16"
description = "Session replay and error monitoring: stop guessing why bugs happen!"
license = "Apache-2.0"
authors = [
    "Vadim Korolik <vadim@highlight.io>",
    "Jay Khatri <jay@highlight.io>",
]
readme = "README.md"
homepage = "https://www.highlight.io"
repository = "https://github.com/highlight/highlight"
documentation = "https://www.highlight.io/docs"
keywords = [
    "web",
    "framework",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Framework :: Flask",
    "Topic :: Software Development",
    "Topic :: System :: Monitoring"
]
packages = [{ include = "highlight_io" }]

[tool.poetry.dependencies]
python = ">=3.8,<4"
blinker = { version = ">=1", optional = true }
django = { version = ">=3", optional = true }
flask = { version = ">=2", optional = true }
fastapi = { version = ">=0", optional = true }
uvicorn = {version = ">=0", extras = ["standard"], optional = true }
celery = { version = ">=5", optional = true }
opentelemetry-instrumentation-celery = { version = "0.43b0", optional = true }
redis = { version = ">=5", optional = true }
opentelemetry-instrumentation-redis = { version = "0.43b0", optional = true }
boto = { version = ">=2", optional = true }
opentelemetry-instrumentation-boto = { version = "0.43b0", optional = true }
boto3 = { version = ">=1", optional = true }
opentelemetry-instrumentation-sqlalchemy = { version = "0.43b0", optional = true }
sqlalchemy = { version = ">=2", optional = true }
opentelemetry-instrumentation-boto3sqs = { version = "0.43b0", optional = true }
opentelemetry-api = "1.22.0"
opentelemetry-distro = { extras = ["otlp"], version = "0.43b0" }
opentelemetry-exporter-otlp-proto-http = "1.22.0"
opentelemetry-instrumentation = "0.43b0"
opentelemetry-instrumentation-logging = "0.43b0"
opentelemetry-proto = "1.22.0"
opentelemetry-sdk = "1.22.0"
opentelemetry-instrumentation-requests = "0.43b0"

[tool.poetry.group.dev.dependencies]
azure-functions = ">=1"
black = ">=22"
functions-framework = ">=3"
pytest = ">=7"
pytest-mock = ">=3"
pytest-cov = ">=4"
pytest-asyncio = ">=0"
loguru = ">=0"
stripe = ">=6"

[tool.poetry.extras]
Boto = ["boto", "opentelemetry-instrumentation-boto"]
Boto3SQS = ["boto3", "opentelemetry-instrumentation-boto3sqs"]
Celery = ["celery", "opentelemetry-instrumentation-celery"]
Django = ["django"]
FastAPI = ["fastapi", "uvicorn"]
Flask = ["blinker", "flask"]
Redis = ["redis", "opentelemetry-instrumentation-redis"]
SQLAlchemy = ["sqlalchemy", "opentelemetry-instrumentation-sqlalchemy"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
