[tool.poetry]
name = "highlight-io"
version = "0.1.2"
description = ""
authors = ["Vadim Korolik <vadim@highlight.io>"]
readme = "README.md"
packages = [{include = "highlight_io"}]

[tool.poetry.dependencies]
python = "^3.10"
opentelemetry-api = "^1.15.0"
opentelemetry-sdk = "^1.15.0"
opentelemetry-proto = "^1.15.0"
flask = "^2.2.2"
opentelemetry-exporter-otlp-proto-http = "^1.15.0"
opentelemetry-instrumentation = "^0.36b0"
opentelemetry-distro = {extras = ["otlp"], version = "^0.36b0"}
opentelemetry-instrumentation-logging = "^0.36b0"
black = "^22.12.0"
blinker = "^1.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
