name: Deploy Screenshots Render Lambda to AWS
on:
    push:
        branches:
            - '**'
        paths:
            - 'render/**'
            - '.github/workflows/deploy-render.yml'
jobs:
    deploy_render:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: 16.14.2
                registry-url: https://registry.npmjs.org
            - name: Build and push lambda
              run: |
                cd render/
                yarn workspaces focus --production
                yarn install
                yarn run build
                yarn run publish
