name: 'Golang SDK code checks'

on:
    push:
        branches: ['main']
    pull_request:
        types: [opened, reopened, synchronize, assigned, review_requested]
        paths:
            - 'sdk/highlight-go/**'
            - '.github/workflows/go-sdk.yml'
    merge_group:

jobs:
    format:
        name: format go files
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Format
              uses: Jerome1337/gofmt-action@v1.0.5
              with:
                  gofmt-path: './sdk/highlight-go'
                  gofmt-flags: '-l -d'

    lint:
        name: lint go files
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run linter
              uses: golangci/golangci-lint-action@v3
              with:
                  args: --config ./.golangci.yaml --timeout 5m
                  working-directory: sdk/highlight-go
                  # version: latest
                  # Pinning the version until https://github.com/golangci/golangci-lint/issues/3862 is solved
                  version: v1.52.2

    build:
        name: build binary
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build binary
              run: cd sdk/highlight-go && go build .

    test-and-cov:
        name: run tests and generate code coverage profile
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 2
            - uses: actions/setup-go@v4
              with:
                  go-version-file: 'backend/go.mod'
            - name: Run tests
              run: cd sdk/highlight-go && go test -race -covermode=atomic -coverprofile=coverage.out --v
