name: 'Golang SDK code checks'

on:
    push:
        branches:
            - '**'
            - '!master'
        paths:
            - 'sdk/highlight-go/**'
            - '.github/workflows/go-sdk.yml'

jobs:
    format:
        name: format go files
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Format
              uses: Jerome1337/gofmt-action@v1.0.4
              with:
                  gofmt-path: './sdk/highlight-go'
                  gofmt-flags: '-l -d'
    lint:
        name: lint go files
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run linter
              uses: golangci/golangci-lint-action@v3
              with:
                  working-directory: sdk/highlight-go/
                  args: --config ./.golangci.yaml
                  version: latest
    build:
        name: build binary
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Build binary
              run: cd sdk/highlight-go && go build .
    test-and-cov:
        name: run tests and generate code coverage profile
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 2
            - uses: actions/setup-go@v2
              with:
                  go-version: '1.19'
            - name: Run tests
              run: cd sdk/highlight-go && go test -race -covermode=atomic -coverprofile=coverage.out --v
