name: Highlight.io Preview Deployment
env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'highlight.io/**'
            - 'docs-content/**'
            - '.github/workflows/highlight-io-preview.yml'
            - 'turbo.json'
            - 'yarn.lock'
jobs:
    Deploy-Preview:
        if: github.event.pull_request.head.repo.full_name == 'highlight/highlight'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: true
            - name: Pull Vercel Environment Information
              run: yarn dlx vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
            - name: Deploy Project Artifacts to Vercel
              run: yarn dlx vercel --token=${{ secrets.VERCEL_TOKEN }}
