name: highlight-run/next
on:
    push:
        paths:
            - 'highlight-next/**'
            - '.github/workflows/highlight-next.yml'
jobs:
    highlight-next:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 16.14.0
                  registry-url: https://registry.npmjs.org
            - name: Install main dependencies
              run: cd highlight-next && yarn install
            - name: Install other dependencies
              run: cd client && yarn install
            # - name: Run tests
            #   run: cd highlight-next && yarn test
            - name: Build Bundle
              run: cd highlight-next && yarn build
            - name: Confirm new version
              run: cd highlight-next && python3 ../scripts/compare.py -s highlight-next
            - name: Publish
              if: github.ref == 'refs/heads/master'
              run: cd highlight-next && yarn publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
