name: Sourcemap Uploader
on:
    push:
        paths:
            - 'sourcemap-uploader/**'
            - '.github/workflows/sourcemap-uploader.yml'
jobs:
    upload:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 16.14.2
                  registry-url: https://registry.npmjs.org
            - name: Install main dependencies
              run: cd sourcemap-uploader && yarn install
            - name: Confirm new version
              run: cd sourcemap-uploader && python3 ../scripts/compare.py -s sourcemap-uploader
            - name: Publish
              if: github.ref == 'refs/heads/master'
              run: cd sourcemap-uploader && yarn npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
